name: Java CI

on:
  push:
    branches: [ main ] # Change 'main' to your default branch if necessary
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11' # Set the Java version you want to use
          distribution: 'temurin' # Use 'temurin' or 'zulu', based on your preference

      - name: Compile Java code
        run: javac UserInterface.java TestUserInterface.java # Compile your classes

      - name: Run the Test Driver
        run: java TestUserInterface # Run the test driver
