name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'  # You can specify other distributions if needed

    - name: Compile Java code
      run: |
        javac LibStage1/UserInterface.java BookTest/TestUserInterface.java

    - name: Run the Test Driver
      run: |
        java -cp LibStage1:BookTest TestUserInterface
